# Lazygit config must be symlinked to ~/Library/Application\ Support/lazygit/.
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  nerdFontsVersion: "3"
  showCommandLog: false
git:
  commit:
    autoWrapCommitMessage: false
  pagers:
    # https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
    - pager: delta --dark --paging=never
      colorArg: always
os:
  editPreset: 'vscode'
update:
  method: 'never'  # disable auto-update
promptToReturnFromSubprocess: false  # directly return to lazygit
